require('a.plugins').setup()
require('a.plugins').initialize_plugins()
require('a.settings')
require('a.utils')
require('a.lsp-settings')
require('a.keybindings')
require('a.augroups')
require('a.statusline').setup()
